# Generated by Django 5.1.7 on 2025-03-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student'),
        ),
        migrations.AddField(
            model_name='faceregistration',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
